- name: copy catalogue,service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

